// Copyright 2026 Betide Studio. All Rights Reserved.

#include "Tools/ReadFileTool.h"
#include "Tools/NeoStackToolUtils.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"

namespace
{
static FString GetPinDefaultValueString(const UEdGraphPin* Pin)
{
	if (!Pin)
	{
		return TEXT("");
	}

	// Prefer explicit object defaults.
	if (Pin->DefaultObject)
	{
		return Pin->DefaultObject->GetPathName();
	}

	// Then text defaults, then scalar/string defaults.
	if (!Pin->DefaultTextValue.IsEmpty())
	{
		return Pin->DefaultTextValue.ToString();
	}

	if (!Pin->DefaultValue.IsEmpty())
	{
		return Pin->DefaultValue;
	}

	// Fall back to autogenerated defaults so agents can still inspect values
	// on unlinked pins (e.g., bool false, enum default selection).
	if (!Pin->AutogeneratedDefaultValue.IsEmpty())
	{
		return Pin->AutogeneratedDefaultValue;
	}

	return TEXT("");
}

static FString BuildPinDefaultsSummary(UEdGraphNode* Node)
{
	if (!Node)
	{
		return TEXT("");
	}

	TArray<FString> PinDefaults;

	for (UEdGraphPin* Pin : Node->Pins)
	{
		if (!Pin)
		{
			continue;
		}

		// Defaults are meaningful for unlinked input pins.
		if (Pin->Direction != EGPD_Input || Pin->LinkedTo.Num() > 0)
		{
			continue;
		}

		// Exec/default-implicit pins are not useful in this section.
		if (Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Exec)
		{
			continue;
		}

		FString DefaultValue = GetPinDefaultValueString(Pin).TrimStartAndEnd();
		if (DefaultValue.IsEmpty())
		{
			continue;
		}

		// Hidden pins are often implicit engine wiring; only include if an explicit
		// default was authored (not just autogenerated fallback noise).
		const bool bHasExplicitDefault =
			Pin->DefaultObject != nullptr ||
			!Pin->DefaultTextValue.IsEmpty() ||
			!Pin->DefaultValue.IsEmpty();
		if (Pin->bHidden && !bHasExplicitDefault)
		{
			continue;
		}

		// Skip noisy implicit object/class "None" defaults.
		const bool bObjectLike =
			Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Object ||
			Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Class ||
			Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_SoftObject ||
			Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_SoftClass;
		if (bObjectLike && DefaultValue.Equals(TEXT("None"), ESearchCase::IgnoreCase))
		{
			continue;
		}

		// Keep node output one-line and tab-safe.
		DefaultValue.ReplaceInline(TEXT("\r"), TEXT(" "));
		DefaultValue.ReplaceInline(TEXT("\n"), TEXT(" "));
		DefaultValue.ReplaceInline(TEXT("\t"), TEXT(" "));

		PinDefaults.Add(FString::Printf(TEXT("%s=%s"), *Pin->PinName.ToString(), *DefaultValue));
	}

	if (PinDefaults.Num() == 0)
	{
		return TEXT("");
	}

	FString Summary = FString::Join(PinDefaults, TEXT("; "));
	constexpr int32 MaxLen = 400;
	if (Summary.Len() > MaxLen)
	{
		Summary = Summary.Left(MaxLen) + TEXT("...");
	}

	return Summary;
}
} // namespace

FString FReadFileTool::GetGraphWithNodes(UEdGraph* Graph, const FString& GraphType, const FString& ParentGraph, int32 Offset, int32 Limit)
{
	if (!Graph)
	{
		return TEXT("# GRAPH (null)\n");
	}

	// Snapshot nodes to avoid crashes if the graph mutates during iteration
	TArray<UEdGraphNode*> NodesSnapshot = Graph->Nodes;
	int32 Total = NodesSnapshot.Num();
	int32 StartIdx = Offset - 1;
	int32 EndIdx = FMath::Min(StartIdx + Limit, Total);

	// Build header
	FString Output;
	if (ParentGraph.IsEmpty())
	{
		Output = FString::Printf(TEXT("# GRAPH %s type=%s %d\n"), *Graph->GetName(), *GraphType, Total);
	}
	else
	{
		Output = FString::Printf(TEXT("# GRAPH %s type=%s parent=%s %d\n"), *Graph->GetName(), *GraphType, *ParentGraph, Total);
	}

	if (Total == 0)
	{
		return Output;
	}

	// Validate indices before iteration
	if (StartIdx < 0)
	{
		StartIdx = 0;
	}
	if (EndIdx > Total)
	{
		EndIdx = Total;
	}

	// Output nodes: guid, title, pins
	for (int32 i = StartIdx; i < EndIdx; i++)
	{
		if (i < 0 || i >= NodesSnapshot.Num())
		{
			// Graph mutated mid-iteration; stop safely
			break;
		}
		UEdGraphNode* Node = NodesSnapshot[i];
		if (!Node || !Node->IsValidLowLevel()) continue;

		FString NodeGuid = NeoStackToolUtils::GetNodeGuid(Node);

		// Safe title retrieval - some nodes (especially AnimGraph nodes) may crash in GetNodeTitle
		// if their internal state has empty arrays or invalid references.
		// AnimGraph nodes inherit from UAnimGraphNode_Base (in AnimGraph module).
		// We detect them by checking if the class belongs to the AnimGraph module, or by
		// checking for known class name patterns. We use the class's GetOutermost() package
		// name to detect AnimGraph module nodes without adding a hard dependency.
		FString NodeTitle;
		{
			FString FallbackName = Node->GetClass()->GetName();
			bool bSafeToGetTitle = true;

			// Check if this node's class comes from the AnimGraph module
			// All UAnimGraphNode_Base subclasses live in /Script/AnimGraph
			UPackage* ClassPackage = Node->GetClass()->GetOutermost();
			if (ClassPackage)
			{
				FString PackageName = ClassPackage->GetName();
				if (PackageName.Contains(TEXT("AnimGraph")) || PackageName.Contains(TEXT("AnimationBlueprintLibrary")))
				{
					bSafeToGetTitle = false;
				}
			}

			// Also catch by class name patterns as a safety net
			if (bSafeToGetTitle)
			{
				FString ClassName = Node->GetClass()->GetName();
				if (ClassName.Contains(TEXT("AnimGraphNode")) ||
				    ClassName.Contains(TEXT("AnimState")) ||
				    ClassName.Contains(TEXT("Transition")) ||
				    ClassName.Contains(TEXT("StateMachine")))
				{
					bSafeToGetTitle = false;
				}
			}

			if (bSafeToGetTitle)
			{
				if (Node->GetGraph() && Node->GetGraph()->GetSchema())
				{
					NodeTitle = Node->GetNodeTitle(ENodeTitleType::ListView).ToString();
				}
				else
				{
					bSafeToGetTitle = false;
				}
			}

			if (!bSafeToGetTitle || NodeTitle.IsEmpty())
			{
				NodeTitle = FallbackName;
			}
		}

		FString PinNames = GetNodePins(Node);

		// Position is always available on UEdGraphNode
		int32 PosX = Node->NodePosX;
		int32 PosY = Node->NodePosY;

		// Size: prefer stored dimensions (comment nodes), then estimate, then defaults
		int32 EstWidth = Node->NodeWidth > 0 ? Node->NodeWidth : 250;
		int32 EstHeightInt = Node->NodeHeight > 0 ? Node->NodeHeight : 100;
		if (Node->NodeHeight <= 0)
		{
			float EstHeight = UEdGraphSchema_K2::EstimateNodeHeight(Node);
			if (EstHeight > 0.0f)
			{
				EstHeightInt = FMath::RoundToInt32(EstHeight);
			}
		}

		const FString PinDefaults = BuildPinDefaultsSummary(Node);
		const FString DefaultsSuffix = PinDefaults.IsEmpty()
			? TEXT("")
			: FString::Printf(TEXT(" defaults=%s"), *PinDefaults);

		Output += FString::Printf(TEXT("%s\t%s\t%s\tpos=%d,%d\tsize=%d,%d%s\n"),
			*NodeGuid, *NodeTitle, *PinNames,
			PosX, PosY, EstWidth, EstHeightInt, *DefaultsSuffix);
	}

	return Output;
}

FString FReadFileTool::GetGraphConnections(UEdGraph* Graph)
{
	TArray<FString> Connections;

	for (UEdGraphNode* Node : Graph->Nodes)
	{
		if (!Node) continue;

		FString FromGuid = NeoStackToolUtils::GetNodeGuid(Node);

		for (UEdGraphPin* Pin : Node->Pins)
		{
			if (Pin->Direction == EGPD_Output && Pin->LinkedTo.Num() > 0)
			{
				for (UEdGraphPin* LinkedPin : Pin->LinkedTo)
				{
					UEdGraphNode* LinkedNode = LinkedPin->GetOwningNode();
					if (LinkedNode)
					{
						FString ToGuid = NeoStackToolUtils::GetNodeGuid(LinkedNode);
						Connections.Add(FString::Printf(TEXT("%s\t%s\t%s\t%s"),
							*FromGuid, *Pin->PinName.ToString(),
							*ToGuid, *LinkedPin->PinName.ToString()));
					}
				}
			}
		}
	}

	FString Output = FString::Printf(TEXT("# CONNECTIONS %s %d\n"), *Graph->GetName(), Connections.Num());
	for (const FString& Conn : Connections)
	{
		Output += Conn + TEXT("\n");
	}

	return Output;
}

FString FReadFileTool::GetNodePins(UEdGraphNode* Node)
{
	return NeoStackToolUtils::GetNodePinNames(Node);
}
